version: "3"
services:
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "3001:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - bombernet
    bomber:
        image: de.cofinpro.dojo/bomber:1.0-SNAPSHOT
        deploy:
            replicas: 1
        ports:
            - "3000:8080"
        networks:
            - bombernet
networks:
    bombernet:
